modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"

[[mods]]
modId="story_engine"
version="${mod_version}"
displayName="Story Engine"
authors="Lorikowka"
description='''
Сюжетный движок для Minecraft: журнал квестов с авто-отслеживанием и сюжетный чат с иконками NPC.
'''

[[dependencies.story_engine]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.story_engine]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
